name: Deploy Public Assets

on:
  push:
    branches: [ main ]
    paths:
      - 'widgets/core/**'
      - 'widgets/webflow-templates/**'
      - '.github/workflows/deploy-public-assets.yml'

jobs:
  deploy-public-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Create public dist directory
        run: |
          mkdir -p dist
      
      - name: Copy widget core files
        run: |
          cp widgets/core/widget.js dist/
          cp widgets/core/widget.min.js dist/
          cp widgets/core/widget-styles.css dist/
          cp widgets/core/widget.d.ts dist/
      
      - name: Copy webflow templates
        run: |
          mkdir -p dist/webflow-templates
          cp -r widgets/webflow-templates/* dist/webflow-templates/
      
      - name: Copy documentation
        run: |
          cp CLAUDE.md dist/
          mkdir -p dist/docs
          cp widgets/core/COMPONENT-ATTRIBUTES.md dist/docs/
          cp widgets/core/WEBFLOW-IMPLEMENTATION-GUIDE.md dist/docs/
      
      - name: Create README
        run: |
          cat > dist/README.md << 'EOL'
          # Webflow Widget Factory - Public Assets
          
          This branch contains the public assets for the Webflow Widget Factory.
          
          ## Contents
          
          - `widget.js` - Core widget JavaScript
          - `widget.min.js` - Minified widget JavaScript
          - `widget-styles.css` - Widget styles
          - `webflow-templates/` - Webflow component templates
          - `docs/` - Implementation guides and documentation
          
          ## Usage with jsDelivr CDN
          
          You can include these assets directly in your Webflow project:
          
          ```html
          <!-- In Webflow > Project Settings > Custom Code > Head -->
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/dfrankle2/webflow-widget-factory@public-assets/widget-styles.css">
          
          <!-- In Webflow > Project Settings > Custom Code > Footer -->
          <script type="module">
            import WidgetController from 'https://cdn.jsdelivr.net/gh/dfrankle2/webflow-widget-factory@public-assets/widget.min.js';
            
            // Initialize widgets when the DOM is ready
            document.addEventListener('DOMContentLoaded', () => {
              document.querySelectorAll('[data-component="WidgetShell"]').forEach(shell => {
                new WidgetController(shell);
              });
            });
          </script>
          ```
          
          ## Implementation
          
          See the [Implementation Guide](docs/WEBFLOW-IMPLEMENTATION-GUIDE.md) for detailed instructions.
          EOL
      
      - name: Configure Git for GitHub Actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Switch to public-assets branch
        run: |
          git fetch origin public-assets || git checkout --orphan public-assets
          git reset --hard
          git clean -fd
      
      - name: Update public-assets branch
        run: |
          cp -r dist/* .
          rm -rf dist
          
          git add .
          git diff --staged --quiet || git commit -m "Update public assets from commit ${GITHUB_SHA}"
          git push origin public-assets